version: '3.9'

networks:
  app-network:
    driver: bridge

volumes:
  db-data:

services:
  app-gallery:
    build: ./Smart_Gallery_Website
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0.32  
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gallery
    networks:
      - app-network
    volumes:
      - ./db-data:/var/lib/mysql 
